"""
Portfolio & Risk Analytics Engine — deterministic portfolio research analytics.

Research-only. No broker execution, no live allocation.
"""

from researchos.quant_engine.portfolio.contracts import (
    AllocationResult,
    EfficientFrontierPoint,
    EfficientFrontierResult,
    Portfolio,
    PortfolioMetrics,
    RiskContribution,
)
from researchos.quant_engine.portfolio.analytics import (
    mean,
    variance,
    std_dev,
    covariance,
    correlation,
    correlation_matrix,
    covariance_matrix,
    portfolio_returns,
    portfolio_variance,
    max_drawdown,
    equity_curve_from_returns,
    downside_deviation,
    sortino_ratio,
    sharpe_ratio,
    calmar_ratio,
    omega_ratio,
    value_at_risk,
    conditional_var,
    expected_shortfall,
    beta,
    alpha,
    treynor_ratio,
    information_ratio,
    kelly_fraction,
    risk_contributions,
    allocate_capital,
    drawdown_attribution,
    exposure_analytics,
    compute_portfolio_metrics,
    minimum_variance_portfolio,
    maximum_sharpe_portfolio,
    efficient_frontier,
)

__all__ = [
    "AllocationResult",
    "EfficientFrontierPoint",
    "EfficientFrontierResult",
    "Portfolio",
    "PortfolioMetrics",
    "RiskContribution",
    "mean",
    "variance",
    "std_dev",
    "covariance",
    "correlation",
    "correlation_matrix",
    "covariance_matrix",
    "portfolio_returns",
    "portfolio_variance",
    "max_drawdown",
    "equity_curve_from_returns",
    "downside_deviation",
    "sortino_ratio",
    "sharpe_ratio",
    "calmar_ratio",
    "omega_ratio",
    "value_at_risk",
    "conditional_var",
    "expected_shortfall",
    "beta",
    "alpha",
    "treynor_ratio",
    "information_ratio",
    "kelly_fraction",
    "risk_contributions",
    "allocate_capital",
    "drawdown_attribution",
    "exposure_analytics",
    "compute_portfolio_metrics",
    "minimum_variance_portfolio",
    "maximum_sharpe_portfolio",
    "efficient_frontier",
]

