"""
Fundamental Research Engine — deterministic macro research models & analytics.

No online API integration. Research-only.
"""

from researchos.engines.quant.fundamental.analytics import (
    bond_convexity,
    bond_spread,
    bond_spread_series,
    calendar_density,
    classify_policy_action,
    classify_surprise,
    commodity_correlations,
    concentration_by_indicator,
    duration_estimate,
    events_by_country,
    filter_high_severity,
    fisher_real_yield,
    fit_macro_factor_model,
    keyword_sentiment,
    macro_series_statistics,
    normalize_news_event,
    normalize_news_text,
    policy_rate_delta,
    real_yield,
    real_yield_series,
    surprise_score,
    yield_curve_metrics,
    yield_spread_metrics,
)
from researchos.engines.quant.fundamental.contracts import (
    CentralBank,
    CommodityBasket,
    EconomicCalendarEvent,
    EventSeverity,
    MacroDataPoint,
    MacroFactorModel,
    MacroIndicator,
    NewsEvent,
)

__all__ = [
    "CentralBank",
    "CommodityBasket",
    "EconomicCalendarEvent",
    "EventSeverity",
    "MacroDataPoint",
    "MacroFactorModel",
    "MacroIndicator",
    "NewsEvent",
    "surprise_score",
    "classify_surprise",
    "macro_series_statistics",
    "policy_rate_delta",
    "classify_policy_action",
    "yield_curve_metrics",
    "commodity_correlations",
    "bond_convexity",
    "duration_estimate",
    "real_yield",
    "fisher_real_yield",
    "real_yield_series",
    "bond_spread",
    "bond_spread_series",
    "yield_spread_metrics",
    "filter_high_severity",
    "events_by_country",
    "concentration_by_indicator",
    "calendar_density",
    "normalize_news_text",
    "keyword_sentiment",
    "normalize_news_event",
    "fit_macro_factor_model",
]
