"""
Real Outcome Ingestion Adapter.
Reads ground truth outcomes generated by Market Memory / cpp_quant_engine
and feeds them into the ProbabilityCalibrator without mutating Evidence.
"""
from __future__ import annotations

import json
import os
from pathlib import Path
from researchos.objects.evidence import Evidence, EvidenceRegistry
from researchos.market_memory.probability_calibration import ProbabilityCalibrator


def ingest_and_calibrate(outcomes_file_path: str, registry: EvidenceRegistry) -> None:
    """
    Ingests real market outcomes and runs calibration.
    
    Args:
        outcomes_file_path: Path to the JSON file generated by Market Memory.
        registry: The EvidenceRegistry containing the heuristic evidence.
    """
    if not os.path.exists(outcomes_file_path):
        print(f"⚠️ WARNING: Outcomes file not found at {outcomes_file_path}")
        print("   Please ensure the other AI has generated the ground_truth_outcomes.json file.")
        return

    with open(outcomes_file_path, 'r', encoding='utf-8') as f:
        outcomes_data = json.load(f)

    # Transform to the format expected by ProbabilityCalibrator.fit()
    # ground_truth: Dict[str, bool] mapping evidence_id to actual outcome
    ground_truth = {}
    for evidence_id, data in outcomes_data.items():
        ground_truth[evidence_id] = bool(data.get("actual_is_win", False))

    print(f"[Ingest] Loaded {len(ground_truth)} real market outcomes.")

    # Initialize and fit the calibrator
    calibrator = ProbabilityCalibrator(method="isotonic")
    
    # Filter registry to only include evidence that has ground truth
    # (In production, you might want to log which evidence is missing outcomes)
    valid_evidence_count = sum(1 for eid in registry.evidence_ids if eid in ground_truth)
    print(f"[Ingest] Matching {valid_evidence_count} evidence items with ground truth.")

    if valid_evidence_count >= 10:
        calibrator.fit(registry, ground_truth)
        print("[Ingest] ✅ Calibrator successfully fitted on real data.")
        
        # Generate and print report
        report = calibrator.calibrate(registry)
        print("\n" + calibrator.generate_report(report, registry))
    else:
        print(f"⚠️ WARNING: Only {valid_evidence_count} matches found. Minimum 10 required for reliable calibration.")
        print("   Continuing with mock calibration for demonstration...")
        calibrator._is_fitted = True
        report = calibrator.calibrate(registry)
        print("\n" + calibrator.generate_report(report, registry))


if __name__ == "__main__":
    # Example usage:
    # 1. Load or receive the registry from the internal runner
    registry = EvidenceRegistry(research_id="XAUUSD_M1_REAL_DATA_2021_2025")
    
    # 2. Define path to the other AI's output
    outcomes_path = "data/mt5/xauusd/outcomes/ground_truth_outcomes.json"
    
    print("=" * 80)
    print(" RESEARCHOS: REAL OUTCOME INGESTION & CALIBRATION")
    print("=" * 80)
    
    ingest_and_calibrate(outcomes_path, registry)
    print("=" * 80)