"""
Pipeline Validation Orchestrator.
This script sits OUTSIDE the production runner. 
It takes the EvidenceRegistry generated by the internal runner, 
validates it against the 8 invariants and synthetic boundaries, 
and reports the scientific integrity of the XAUUSD M1 pipeline.
"""
from __future__ import annotations

from datetime import datetime, timezone
from researchos.objects.evidence import Evidence, EvidenceRegistry
from researchos.experiments.external_validator import EvidenceChainValidator
from researchos.experiments.synthetic_boundary import SyntheticBoundaryChecker


def run_pipeline_validation():
    print("="*80)
    print(" RESEARCHOS: XAUUSD M1 REAL DATA PIPELINE VALIDATION")
    print("="*80)
    
    # 1. Initialize Registry (This would normally be passed from the internal runner)
    # For demonstration, we simulate the handoff from the internal Market Memory pipeline
    registry = EvidenceRegistry(research_id="XAUUSD_M1_REAL_DATA_2021_2025")
    
    # --- SIMULATED INTERNAL RUNNER OUTPUT (Replace with actual handoff later) ---
    # The other AI's internal runner would append evidence like this:
    valid_evidence = Evidence(
        observation_id="OBS|EXP_XAUUSD_001|RUN_WFO_001|a1b2c3d4e5f6g7h8",
        hypothesis_id="HYP_XAUUSD_SMC_001",
        interpretation="Walk-forward OOS evaluation on real XAUUSD M1 data shows positive expectancy. Win rate 58%, PF 1.8.",
        direction="Supporting",
        source_reliability=0.95,
        recency=0.90,
        relevance=0.95,
        consensus=0.85,
        structural_importance=0.90,
        quality_factor=0.95,
        uncertainty=0.10,
        tier="Primary"
    )
    registry.add_evidence(valid_evidence)
    # ----------------------------------------------------------------------------

    print(f"\n[1/3] Loaded Registry: {registry.research_id}")
    print(f"       Total Evidence Items: {len(registry.evidence)}")

    # 2. Run External Evidence Chain Validator (8 Invariants)
    print("\n[2/3] Running External Evidence Chain Validator (8 Invariants)...")
    chain_validator = EvidenceChainValidator(registry)
    chain_passed, chain_violations = chain_validator.validate_all()
    
    if chain_passed:
        print("       ✅ PASSED: All 8 architectural invariants are satisfied.")
    else:
        print("       ❌ FAILED: Invariant violations detected:")
        for v in chain_violations:
            print(f"          - {v}")

    # 3. Run Synthetic Boundary Checker
    print("\n[3/3] Running Synthetic-Data Boundary Checker...")
    boundary_checker = SyntheticBoundaryChecker(registry)
    boundary_passed = boundary_checker.validate_no_mixing()
    
    if boundary_passed:
        print("       ✅ PASSED: No mixing of synthetic and real data detected.")
    else:
        print("       ❌ FAILED: Synthetic and real data are mixed in the same registry.")

    # 4. Final Verdict
    print("\n" + "="*80)
    if chain_passed and boundary_passed:
        print(" FINAL VERDICT: ✅ PIPELINE INTEGRITY VERIFIED")
        print(" The evidence chain is deterministic, immutable, and scientifically sound.")
        print(" Ready to proceed to Probability Calibration.")
    else:
        print(" FINAL VERDICT: ❌ PIPELINE INTEGRITY COMPROMISED")
        print(" Do not proceed to calibration. Fix internal runner violations first.")
    print("="*80 + "\n")
    
    return chain_passed and boundary_passed


if __name__ == "__main__":
    success = run_pipeline_validation()
    exit(0 if success else 1)
